<?php

/**
 * Module file for ap_reviews.
 */

/*
 * Implements hook_preprocess_page().
 */

function ap_reviews_preprocess_page(&$variables) {
  $request = drupal_http_request('http://www.goodreads.com/search.xml?key=7CgTGOmUrl10oipPl9aa2Q&q=Ender%27s+Game');
//  dpm($request, 'request');
  $requestData = $request->data;
  $finalData = simplexml_load_string($requestData);
//  dpm($requestData, 'data');
//  dpm($finalData, 'dataFinal');

}